### ISSUE TITLE
record s3a metrics

### ISSUE THREAD

**Issue by sjrand** [palantir/spark#126]
s3a includes various metrics in hadoop 2.8: https://github.com/palantir/hadoop/blob/branch-2.8.0/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3AInstrumentation.java

It looks like to get them, we need to call `FileSystem#getGlobalStorageStatistics` from the process that creates a new instance of `S3AFileSystem`, which from my understanding will be either an executor or the driver: https://github.com/palantir/hadoop/blob/branch-2.8.0/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L3585

From there send them to the configured sink.

**Comment by tstearns** [comment]
Are there any examples of hadoop-ecosystem tools doing this already? I did some simple grepping in hadoop and spark repos without any luck, but it seems odd that this new stats system would be put in place without other projects calling it somehow?

**Comment by robert3005** [comment]
@sjrand how would this look like? Want to make a pr?

**Comment by sjrand** [comment]
Actually this may not be something that Spark has to do at all. From https://issues.apache.org/jira/browse/HADOOP-14475, it looks like it's more a matter of configuring `metrics.properties`.

Closing for now at least.
