### ISSUE TITLE
Test flake: SparkSubmitSuite and HiveSparkSubmitSuite

### ISSUE THREAD

**Issue by ash211** [palantir/spark#134]
https://circleci.com/gh/palantir/spark/573#artifacts/containers/0

- `SparkSubmitSuite`:
  - `[info] - include an external JAR in SparkR *** FAILED *** (5 seconds, 368 milliseconds)`
- `RecurringTimerSuite`:
  - `[info] - SPARK-10224: call 'callback' after stopping *** FAILED *** (10 milliseconds)`
- `HiveSparkSubmitSuite`:
  - `[info] - SPARK-9757 Persist Parquet relation with decimal column *** FAILED *** (5 minutes, 0 seconds)`

**Comment by ash211** [comment]
https://circleci.com/gh/palantir/spark/576

- `org.apache.spark.deploy.SparkSubmitSuite`
  - `includes jars passed in through --packages`

**Comment by ash211** [comment]
@robert3005 how do you feel about ignoring all of `SparkSubmitSuite` and `HiveSparkSubmitSuite` since they're flakey?  I think the main risk is that a regression in normal spark submission could be introduced by the kubernetes work since that's in the realm of the submission process.

@mccheah for thoughts on whether we should root cause `(Hive|)SparkSubmitSuite` flakes or stop running the tests for now.

**Comment by robert3005** [comment]
Strongly against disabling these. We mess with the submission changes too much for this to not backfire. #115 was one of such changes.

**Comment by ash211** [comment]
So just live with the flakes until we can't stand them anymore?

**Comment by robert3005** [comment]
First person to get annoyed gets to fix it. If you disable those tests we will likely merge something we shouldn't have.

**Comment by robert3005** [comment]
More concretely #130 causes a break in one of those tests and probably affects sparkr submit process. Given that it's possible to break these with packaging changes I would like to keep them on. I haven't seen them flake since we refactored the test setup.
