### ISSUE TITLE
Modify file coalescing algorithm to preserve order

### ISSUE THREAD

**Issue by ash211** [palantir/spark#153]
http://apache-spark-developers-list.1001551.n3.nabble.com/Sorting-within-partitions-is-not-maintained-in-parquet-tp18618p18627.html

Can we maintain sorting between file partitions by modifying the file coalescing algorithm to preserve file order?

https://issues.apache.org/jira/browse/SPARK-8813
https://issues.apache.org/jira/browse/SPARK-13664
https://github.com/apache/spark/pull/12095

**Comment by robert3005** [comment]
What's the use case? I think no one should be depending on order of files

**Comment by ash211** [comment]
Preview of sorted datasets should remain sorted.  Ping me for internal tickets

**Comment by robert3005** [comment]
Agreed, this is a wrong solution though. If you sort we should store the
sort and apply it on reading

**Comment by ash211** [comment]
If our external catalog change stores any sorting constraints on save and initializes new Dataframes with that sorting, and also Spark respects the sort even during file load then we're good.  But I'm skeptical the second part happens right now.  We'll have to get to that once the external catalog change is farther along

**Comment by robert3005** [comment]
That's how it works. Currently there's no guarantee (even when sorting)
that output order is preserved

**Comment by ash211** [comment]
https://issues.apache.org/jira/browse/SPARK-20144
