### ISSUE TITLE
Standalone ORC fileformat

### ISSUE THREAD

**Issue by robert3005** [palantir/spark#157]
We don't need all of spark-hive. Orc only depends on hive-storage-api which is a lot smaller than hive-exec

**Comment by robert3005** [comment]
Upstream issue https://issues.apache.org/jira/browse/SPARK-20682

**Comment by ash211** [comment]
It's been merged!  Should be able to remove the Hive profile in Palantir Spark and yet still retain support for ORC in the resulting dist.
