### ISSUE TITLE
Bump dependencies to latest versions for a used major 

### ISSUE THREAD

**Issue by robert3005** [palantir/spark#174]
I think we can be a bit more aggressive about bumping versions

currently thinking about 
- [ ] joda-time 2.9.3 => 2.9.9
- [ ] okhttp 2.4.0 => 2.7.5 
- [ ] okio 1.6.0 => 1.13.0
- [ ] okhttp3 3.6.0 => 3.7.0
- [ ] antlr4-runtime 4.5.3 => 4.7.0
- [ ] maven 3.3.9 => 3.5.0
- [ ] slf4j 1.7.16 => 1.7.25
- [ ] jsr305 1.3.9 => 3.0.1
- [ ] RoaringBitMap 0.5.11 => 0.6.43
- [ ] netty-all 4.0.43.Final => 4.1.9.Final
- [ ] netty 3.9.9.Final => 3.10.6.Final (last release)
- [ ] jetty 9.2.16.v20160414 => 9.4.4.v20170414
- [ ] jersey 2.22.2 => 2.25.1

**Comment by ash211** [comment]
I'm good with trying this in an RC and making sure it works with some internal apps
