### ISSUE TITLE
Remove credentials out of URLs from all conda output

### ISSUE THREAD

**Issue by dansanduleac** [palantir/spark#211]
When `spark.conda.verbosity` is more than 0, channel URLs might be printed unsanitised, which can include credentials / auth tokens.

We should preprocess the logs, parsing out any:
* basic auth e.g. `https://user:pass@...`
* tokens in the URL e.g. `https://.../t/token-contents/`

**Comment by jeremyjliu** [comment]
@dansanduleac Is this ticket closable with https://github.com/palantir/spark/pull/185?
