### ISSUE TITLE
Run k8s integration tests in CI

### ISSUE THREAD

**Issue by ash211** [palantir/spark#257]
Would've caught the issue that #255 fixed because it was only present in the combination of 1) Apache master branch and 2) the apache-spark-on-k8s features

Troublesome/unsupported to set up minikube in circle though:
- https://discuss.circleci.com/t/running-virtualized-minikube/14052
- https://discuss.circleci.com/t/state-changes-between-run-stanzas/15925

**Comment by rynorris** [comment]
This guy claims to have minikube running in circle.  Might be worth a go now: https://github.com/gavinzhou/ci-minikube
