### ISSUE TITLE
Memory pressure in ParquetFileSplitter

### ISSUE THREAD

**Issue by ash211** [palantir/spark#259]
Possible fixes:

- stop interning in parquet: https://github.com/apache/parquet-format/pull/2/files#diff-9cf0e719107ec5ee2a0e73a1693dfd00L38
  - interning Strings often an antipattern, at least in older JDKs they went into PermGen and were very difficult to GC.  This kills us for long-lived JVMs
- bound cache at https://github.com/palantir/spark/blob/2.3.0-palantir.16/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileSplitter.scala#L67
  - probably real small but unbounded caches are bad
- remove reference to blocks in ParquetMetadataFileSplitter

cc @robert3005

**Comment by schlosna** [comment]
definitely worth testing alternatives for parquet's interning, see https://shipilev.net/jvm-anatomy-park/10-string-intern/ and also [G1 GC's string deduplication via `-XX:+UseG1GC -XX:+UseStringDeduplication -XX:+PrintStringDeduplicationStatistics`](http://openjdk.java.net/jeps/192)

**Comment by ash211** [comment]
Ryan Norris observed a driver stuck in this stacktrace for quite some time:

![pasted image at 2017_09_13 06_15 pm](https://user-images.githubusercontent.com/357170/30411244-920e490c-98c4-11e7-898b-c83a092097ed.png)

**Comment by robert3005** [comment]
Created https://github.com/apache/parquet-format/pull/92 with https://issues.apache.org/jira/browse/PARQUET-1261

**Comment by robert3005** [comment]
This is due to string interning and cms that can be fixed by switching to g1/zgc/shenandoah
