### ISSUE TITLE
Backport Josh's correctness fixes

### ISSUE THREAD

**Issue by ash211** [palantir/spark#298]
Lots of correctness stuff coming in over the past few days: https://issues.apache.org/jira/issues/?jql=project%20%3D%20SPARK%20AND%20reporter%20in%20(joshrosen)%20ORDER%20BY%20key%20DESC%2C%20priority%20DESC%2C%20updated%20DESC

- https://issues.apache.org/jira/browse/SPARK-22982
- https://issues.apache.org/jira/browse/SPARK-22983
- https://issues.apache.org/jira/browse/SPARK-22984
- https://issues.apache.org/jira/browse/SPARK-22985
- https://issues.apache.org/jira/browse/SPARK-22997

**Comment by robert3005** [comment]
All of them are already in master.
