### ISSUE TITLE
waitAppCompletion should allow the client get the app id

### ISSUE THREAD

**Issue by onursatici** [palantir/spark#304]
Currently Spark does not provide a way to get the appId and not monitor the application from the handle. We should have a way to turn on fire and forget, get the appId and not worry about spark submit processes.

Details:
https://github.com/palantir/spark/blob/master/resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala#L1147
above shows fireAndForget is not effective when the client is connected to the launcher backend. We need to keep the connection alive to get the app id, so the only way we can do now is time the disconnect call through the handle perfectly so we hit client just after it sent the app id and is about the check for connection on the code path above. This is nearly impossible to do so we need to have a better way here

**Comment by robert3005** [comment]
Please file upstream - this sounds like a general issue that can be easily addressed there.

You should use in memory spark process launcher in the meantime

**Comment by onursatici** [comment]
Yeah, will PR upstream and file a jira issue. Just opened this to track until we do that

**Comment by robert3005** [comment]
Is this fixed upstream? Can you link the ticket?
