### ISSUE TITLE
SparkUI reports (some) terminated k8s exec pods as alive

### ISSUE THREAD

**Issue by jamding** [palantir/spark#322]
I have a spark job with 3 terminated k8s executor pods due to OOM:

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to java_pid16.hprof ...
Heap dump file created [5908598695 bytes in 52.630 secs]
Aborting due to java.lang.OutOfMemoryError: GC overhead limit exceeded
```
and k8s/kubectl report 3 pods as failing. 

![screen shot 2018-02-28 at 3 22 03 pm](https://user-images.githubusercontent.com/5925684/36818730-2f1b9b96-1c9b-11e8-82dd-ca489d5636bc.png)

However SparkUI reports 1 of the executors as dead, but not the other 2. 

![screen shot 2018-02-28 at 3 23 53 pm](https://user-images.githubusercontent.com/5925684/36818790-87d0dab2-1c9b-11e8-9e3f-faac927cbc66.png)

and from the _/api/v1/applications/<app>/allexecutors_:

```
[ {
  "id" : "1",
  "hostPort" : "<host>:41733",
  "isActive" : true,
  "rddBlocks" : 0,
  "memoryUsed" : 0,
  "diskUsed" : 0,
  "totalCores" : 2,
  "maxTasks" : 2,
  "activeTasks" : 1,
  "failedTasks" : 2,
  "completedTasks" : 3,
  "totalTasks" : 6,
  "totalDuration" : 659628,
  "totalGCTime" : 6963,
  "totalInputBytes" : 62970658,
  "totalShuffleRead" : 1131041,
  "totalShuffleWrite" : 583268097,
  "isBlacklisted" : false,
  "maxMemory" : 3515665612,
  "addTime" : "2018-02-28T22:38:36.799GMT",
  "executorLogs" : { },
  "memoryMetrics" : {
    "usedOnHeapStorageMemory" : 0,
    "usedOffHeapStorageMemory" : 0,
    "totalOnHeapStorageMemory" : 3515665612,
    "totalOffHeapStorageMemory" : 0
  }
}, {
  "id" : "2",
  "hostPort" : "<host>:43781",
  "isActive" : true,
  "rddBlocks" : 0,
  "memoryUsed" : 0,
  "diskUsed" : 0,
  "totalCores" : 2,
  "maxTasks" : 2,
  "activeTasks" : 1,
  "failedTasks" : 4,
  "completedTasks" : 3,
  "totalTasks" : 8,
  "totalDuration" : 729233,
  "totalGCTime" : 12390,
  "totalInputBytes" : 62235782,
  "totalShuffleRead" : 0,
  "totalShuffleWrite" : 582135729,
  "isBlacklisted" : false,
  "maxMemory" : 3515665612,
  "addTime" : "2018-02-28T22:38:39.041GMT",
  "executorLogs" : { },
  "memoryMetrics" : {
    "usedOnHeapStorageMemory" : 0,
    "usedOffHeapStorageMemory" : 0,
    "totalOnHeapStorageMemory" : 3515665612,
    "totalOffHeapStorageMemory" : 0
  }
}, {
  "id" : "3",
  "hostPort" : "<host>:42601",
  "isActive" : false,
  "rddBlocks" : 0,
  "memoryUsed" : 0,
  "diskUsed" : 0,
  "totalCores" : 2,
  "maxTasks" : 2,
  "activeTasks" : 2,
  "failedTasks" : 0,
  "completedTasks" : 2,
  "totalTasks" : 4,
  "totalDuration" : 184416,
  "totalGCTime" : 13525,
  "totalInputBytes" : 65458759,
  "totalShuffleRead" : 0,
  "totalShuffleWrite" : 582140934,
  "isBlacklisted" : false,
  "maxMemory" : 3515665612,
  "addTime" : "2018-02-28T22:38:43.250GMT",
  "removeTime" : "2018-02-28T22:46:32.799GMT",
  "removeReason" : "Executor lost for unknown reasons.",
  "executorLogs" : { },
  "memoryMetrics" : {
    "usedOnHeapStorageMemory" : 0,
    "usedOffHeapStorageMemory" : 0,
    "totalOnHeapStorageMemory" : 3515665612,
    "totalOffHeapStorageMemory" : 0
  }
}, {
  "id" : "driver",
  "hostPort" : "<host>:7079",
  "isActive" : true,
  "rddBlocks" : 0,
  "memoryUsed" : 0,
  "diskUsed" : 0,
  "totalCores" : 0,
  "maxTasks" : 0,
  "activeTasks" : 0,
  "failedTasks" : 0,
  "completedTasks" : 0,
  "totalTasks" : 0,
  "totalDuration" : 0,
  "totalGCTime" : 0,
  "totalInputBytes" : 0,
  "totalShuffleRead" : 0,
  "totalShuffleWrite" : 0,
  "isBlacklisted" : false,
  "maxMemory" : 2280967372,
  "addTime" : "2018-02-28T22:38:17.352GMT",
  "executorLogs" : { },
  "memoryMetrics" : {
    "usedOnHeapStorageMemory" : 0,
    "usedOffHeapStorageMemory" : 0,
    "totalOnHeapStorageMemory" : 2280967372,
    "totalOffHeapStorageMemory" : 0
  }
} ]
```

**Comment by jamding** [comment]
Probably related: the stages view in the UI reports there's an active task even though all 3 executor pods have terminated. Job then hangs for hours (at least) because there are no executors to run any tasks.

![screen shot 2018-02-28 at 3 30 29 pm](https://user-images.githubusercontent.com/5925684/36819520-a8cbe7ae-1c9e-11e8-92a5-dfd190bcd1e1.png)

**Comment by robert3005** [comment]
@mccheah are you tracking this?

**Comment by jamding** [comment]
@robert3005 tracked on our internal support jira, but this happens when our spark module's restricted driver oauth token doesn't have authorization to delete resources in the namespace for the job. With this specific job the second executor times out to a heartbeat so its marked as lost, then when the k8s spark client attempts to [kill the executor pod through the fabric8 client](https://github.com/palantir/spark/blob/master/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/k8s/KubernetesClusterSchedulerBackend.scala#L311), it fails because it isn't authorized and the spark job is left in a bad state that we see in the issue.

In driver logs I found: 
`WARN  [2018-02-28T22:57:15.704Z] org.apache.spark.HeartbeatReceiver: Removing executor 1 with no recent heartbeats: 333874 ms exceeds timeout 300000 ms
ERROR [2018-02-28T22:57:15.704Z] org.apache.spark.scheduler.cluster.k8s.KubernetesTaskSchedulerImpl: Lost executor 1 on 10.255.79.231: Executor heartbeat timed out after 333874 ms
WARN  [2018-02-28T22:57:15.705Z] org.apache.spark.scheduler.cluster.k8s.KubernetesTaskSetManager: Lost task 0.0 in stage 5.1 (TID 11, 10.255.79.231, executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 333874 ms
WARN  [2018-02-28T22:57:15.705Z] org.apache.spark.scheduler.cluster.k8s.KubernetesTaskSetManager: Lost task 1.0 in stage 5.1 (TID 12, 10.255.79.231, executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 333874 ms
INFO  [2018-02-28T22:57:15.71Z]  org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend: Requesting to kill executor(s) 1
INFO  [2018-02-28T22:57:15.717Z] org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend: Actual list of executor(s) to be killed is 1
ERROR [2018-02-28T22:57:15.885Z] org.apache.spark.util.Utils: Uncaught exception in thread kill-executor-thread (throwable0_message: Exception thrown in awaitResult: , throwable1_message: Failure executing: DELETE at: https://kubernetes.default.svc/api/v1/namespaces/smm-rubix-f072bb0b693c4b758b2edec2041c2230/pods/smm-1debc0931c4d4ceca6ddf373181334e0-1519857442311-exec-1. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "smm-1debc0931c4d4ceca6ddf373181334e0-1519857442311-exec-1" is forbidden: User "smm-rubix" cannot delete pods in the namespace "smm-rubix-f072bb0b693c4b758b2edec2041c2230".)`
