### ISSUE TITLE
Re-enable arrow tests

### ISSUE THREAD

**Issue by dansanduleac** [palantir/spark#328]
Currently, some arrow tests are failing because of weird behaviour around timestamps, so we've disabled them.

Tests disabled  in https://github.com/palantir/spark/pull/326/commits/52cbda2e67cf37346f0ca7f90a2f5a8659447d1d

**Comment by vinooganesh** [comment]
As part of https://issues.apache.org/jira/browse/SPARK-26032 in https://github.com/apache/spark/pull/23021, these tests were moved and reenabled
