### ISSUE TITLE
have registering a metrics source handle newly added metrics

### ISSUE THREAD

**Issue by bavardage** [palantir/spark#53]
current behaviour:
spark only sees the metrics that are in the metrics registry of your source at the time of registration

possible fix:
use a metrics listener to do the registration

**Comment by robert3005** [comment]
@bavardage This is already handled via Source trait. Then in metrics.properties you can either provide a class to enable or you can call SparkEnv.metricsSystem.registerSource. Also made #214  which will let you use SharedMetricRegistries

**Comment by robert3005** [comment]
Fixed in #214
