### ISSUE TITLE
Support for external catalogs in Spark SQL

### ISSUE THREAD

**Issue by ash211** [palantir/spark#67]
Would rather have an official API point for setting external catalogs into a `SparkSession` rather than using reflection to set the catalog on `SessionState` as we are right now.

```
setFieldOnClass(sparkSession.sessionState(), "catalog", myCustomCatalog);
```

There was an API break between Spark 2.0.0 and 2.1.0 where its constructor changed and we had to accommodate that.

**Comment by ash211** [comment]
PR sent upstream here: https://github.com/apache/spark/pull/16963

**Comment by ash211** [comment]
There was another API break on Jan 11 where the SessionState constructor changed which affected us: https://github.com/apache/spark/commit/30a07071f099c0ebcf04c4df61f8d414dcbad7b5#diff-06e7b9d9e1afd7aca1a3b2cd18561953R103

**Comment by robert3005** [comment]
tracked in #128
